


export const keywords = [
    "utilidades domésticas",
    "produtos de iluminação",
    "iluminação residencial",
    "iluminação comercial",
    "abajures",
    "luminárias",
    "lâmpadas",
    "luzes LED",
    "luzes de teto",
    "luzes de parede",
    "luzes de chão",
    "iluminação exterior",
    "decoração de iluminação",
    "fornecimento de iluminação",
    "acessórios de iluminação",
    "luzes modernas",
    "luzes clássicas",
    "luzes vintage",
    "luzes contemporâneas",
    "iluminação energicamente eficiente",
    "iluminação personalizada",
    "luzes inteligentes",
    "luzes controladas por aplicativo",
    "iluminação de design",
    "iluminação de ambiente",
    "iluminação de escritório",
    "iluminação de cozinha",
    "iluminação de banheiro",
    "iluminação de jardim",
    "iluminação de sala de estar",
    "iluminação de quarto",
    "luzes decorativas",
    "luzes de emergência",
    "luzes de segurança",
    "luzes de destaque",
    "luzes pendentes",
    "luzes embutidas",
    "luzes de trilho",
    "fornecimento de abajures",
    "abajures de mesa",
    "abajures de chão",
    "abajures modernos",
    "abajures clássicos",
    "abajures vintage",
    "abajures contemporâneos",
    "abajures de design",
    "abajures decorativos",
    "abajures de alta qualidade",
    "abajures personalizados",
    "abajures para sala de estar",
    "abajures para quarto",
    "abajures para escritório",
    "abajures para sala de estar",
    "abajures para sala de jantar",
    "abajures para cozinha"
];


