/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/3Joxy58xl4d
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link";
import { JSX, SVGProps } from "react";

export function InitialFooter() {
  return (
    <footer className="flex flex-col items-center justify-between gap-6 py-8 px-4 md:flex-row md:gap-0 md:py-12 md:px-6 bg-gradient-to-r from-blue-100  to-blue-800 text-white">
      <div className="flex items-center gap-4">
        <img
          alt="Logo"
          className="rounded-full"
          height={32}
          src="https://images.tcdn.com.br/img/img_prod/1112215/1652709121_icone-_2_9_1.ico?6627e7696191c"
          style={{
            aspectRatio: "32/32",
            objectFit: "cover",
          }}
          width={32}
        />
        <div className="grid gap-1">
          <h4 className="text-lg font-semibold text-gray-800">JM Luz e Arte</h4>
          <p className="text-sm text-gray-800">
            R. Lucinda Gomes Barreto, 726 - Vila Nova Manchester, São Paulo
          </p>
        </div>
      </div>
      <div className="flex items-center gap-4">
        <Link className="text-gray-400 hover:text-white" href="#">
          <SmartphoneIcon className="h-5 w-5 fill-current" />
          <span className="sr-only">WhatsApp</span>
        </Link>
        <Link className="text-gray-400 hover:text-white" href="#">
          <InstagramIcon className="h-5 w-5 fill-current" />
          <span className="sr-only">Instagram</span>
        </Link>
        <Link className="text-gray-400 hover:text-white" href="#">
          <ShoppingCartIcon className="h-5 w-5 fill-current" />
          <span className="sr-only">E-commerce</span>
        </Link>
      </div>
    </footer>
  );
}

function InstagramIcon(
  props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>
) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <rect width="20" height="20" x="2" y="2" rx="5" ry="5" />
      <path d="M16 11.37A4 4 0 1 1 12.63 8 4 4 0 0 1 16 11.37z" />
      <line x1="17.5" x2="17.51" y1="6.5" y2="6.5" />
    </svg>
  );
}

function ShoppingCartIcon(
  props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>
) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="8" cy="21" r="1" />
      <circle cx="19" cy="21" r="1" />
      <path d="M2.05 2.05h2l2.66 12.42a2 2 0 0 0 2 1.58h9.78a2 2 0 0 0 1.95-1.57l1.65-7.43H5.12" />
    </svg>
  );
}

function SmartphoneIcon(
  props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>
) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <rect width="14" height="20" x="5" y="2" rx="2" ry="2" />
      <path d="M12 18h.01" />
    </svg>
  );
}
